---
name: AuthCAS
version: 1.6
author:
  - 'Olivier Salaun <os AT cru.fr>'
abstract: Client library for JA-SIG CAS 2.0 authentication server
license: perl
requires:
  IO::Socket::SSL: 0
  LWP::UserAgent: 0
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  homepage: https://sourcesup.renater.fr/projects/perlcas/
  repository: https://subversion.renater.fr/perlcas/
provides:
  AuthCAS:
    file: lib/AuthCAS.pm
    version: 1.6
