# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AuthCAS
version:      1.1
version_from: lib/AuthCAS.pm
installdirs:  site
requires:
    IO::Socket::SSL:               0
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
